#  <font color = 'green'> <center> <b>NUMPY</center>

## Importing Library

In [2]:
import numpy as np

## `Table of Contents`

<div class='alert alert-success'>


**1. Converting a List to an array<br>
2. Arange Function<br>
3. Multidimensional Array<br>
4. Size Function<br>
5. Shape Function<br>
    6. Dtype Function<br>
    7. Ndim Function<br>
    8. Zeros and Ones Function<br>
    9. Eye Function<br>
    10. Empty Function<br>
    11. Random Functions:<br>
    -----a) np.random.rand<br>
    -----b) np.random.randint<br>
    -----c) np.random.randn<br>
    12. Reshape function<br>
    13. Linspace Function<br>
    14. Flatten Function<br>
    15. Logspace Function<br>
    16. Copy Function<br>
    17. arr.max() ,  arr.min() ,     arr.sum() functions<br>
    18. Seed function<br>
    19. Sorting in numpy array<br>
    20. Mathematical Operation in Numpy<br>
    -----a) Addition<br>
    -----b) Substraction<br>
    -----c) Multiplication<br>
    -----d) Division<br>
    -----e) Matrix Multiplication<br>
    -----f) Power<br>
    21. Percentile<br>
    22. Descriptive Statistics<br>
    -----a) Mean<br>
    -----b) Median<br>
    -----c) Mode<br>
    -----d) Standard Deviation<br>
    -----e) Variance<br>
    -----f) Skewness<br>
    -----g) Kurtosis<br>
    23. Filtering an numpy array<br>
    24. Transposing an array<br>
    25. Where function<br>
    26. Merging Arrays<br>
    -----a) Using Concatenate<br>
    -----b) Using vstack and hstack<br>
    27. Splitting Arrays<br>
    28. Linear Algebra<br>
    -----a) Determinant<br>
    -----b) Transpose<br>
    -----c) Inverse<br>
    -----d) Eigen Value & Vectors<br>
    -----e) Solving Linear Equations<br>
    29. `Turning Pictures into Numpy arrays`** 
</div>

### 1. Converting a List to an array

In [9]:
lst = [1,2,3,4]

arr = np.array(lst)
print(arr)

[1 2 3 4]


### 2. Arange Function

In [7]:
arr = np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### 3. Multidimensional Array

In [36]:
lst = [[[1,2,3],[4,5,6],[7,8,9]],
        [[1,2,3],[4,5,6],[7,8,9]],
        [[1,2,3],[4,5,6],[7,8,9]]]
arr = np.array(lst)
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### 4. Size Function

In [30]:
lst = [[1,2,3],[4,5,6],[7,8,9],[34,5,5]]
arr = np.array(lst)

print('Total    :', arr.size)
print('Rows     :', arr[:,0].size)
print('Columns  :', arr[0,:].size)

Total    : 12
Rows     : 4
Columns  : 3


### 5. Shape Function

In [18]:
arr.shape

(3, 3, 3)

### 6. Dtype Function

In [31]:
arr.dtype

dtype('int64')

### 7. Ndim Function

In [37]:
arr.ndim

3

### 8. Zeros and Ones Function

In [42]:
np.zeros((5,5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
np.ones((5,5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. Eye Function

In [47]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 10. Empty Function

In [51]:
np.empty(shape = (5,5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 11. Random Functions:

#### 11.1 np.random.rand

In [52]:
arr = np.random.rand(20)
arr

array([0.56609947, 0.74529244, 0.64270708, 0.3476798 , 0.53103136,
       0.82144417, 0.55733098, 0.24582182, 0.85522286, 0.59598078,
       0.81011009, 0.77179089, 0.82543312, 0.2699618 , 0.48269427,
       0.82228883, 0.95132234, 0.6591768 , 0.09647875, 0.01629443])

#### 11.2 np.random.randint

In [54]:
arr = np.random.randint(0,20, 10 )
arr

array([ 2, 10,  2, 12,  3, 14, 11,  4,  5,  1], dtype=int32)

#### 11.3 np.random.randn

In [56]:
arr = np.random.randn(10)
arr

array([-0.46749011,  1.51895843,  0.46376988, -1.817054  ,  1.05277682,
        0.95461514,  1.01549096,  0.36048458,  0.8382607 ,  1.04784159])

#### 11.4 np.random.uniform

In [59]:
arr = np.random.uniform(0,20,10)
arr

array([15.03426603, 12.41059724,  0.35184552, 14.21993266,  1.74969258,
       10.42544566, 15.45699706,  4.85904567,  6.86938539,  0.87844128])

### 12. Reshape function

In [64]:
lst = [[[1,2,3],[4,5,6],[7,8,9],[3,4,5]],
        [[1,2,3],[4,5,6],[7,8,9],[4,5,6]],
        [[1,2,3],[4,5,6],[7,8,9],[6,7,8]]]

arr = np.array(lst)
arr.shape
arr1 = arr.reshape(4,3,3)
arr1.shape

(4, 3, 3)

### 13. Linspace Function

In [66]:
arr = np.linspace(0,100,10)
arr

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### 14. Flatten Function

In [72]:
lst = [[[1,2,3],[4,5,6],[7,8,9],[3,4,5]],
        [[1,2,3],[4,5,6],[7,8,9],[4,5,6]],
        [[1,2,3],[4,5,6],[7,8,9],[6,7,8]]]

arr = np.array(lst)
arr.shape
arr1 = arr.flatten()
arr1.shape

(36,)

### 15. Logspace Function

In [73]:
arr = np.logspace(0,100,10)
arr

array([1.00000000e+000, 1.29154967e+011, 1.66810054e+022, 2.15443469e+033,
       2.78255940e+044, 3.59381366e+055, 4.64158883e+066, 5.99484250e+077,
       7.74263683e+088, 1.00000000e+100])

### 16. Copy Function

In [78]:
lst = [1,2,3,4,455,4,3,3]
arr = np.array(lst)
arr1 = arr
print(id(arr))
print(id(arr1))
print('-'*20)

arr2 = arr.copy()
print(id(arr))
print(id(arr2))

2238568015856
2238568015856
--------------------
2238568015856
2238568015760


### 17. arr.max() , arr.min() , arr.sum() functions

In [93]:
arr = np.random.randint(0,100,(3,5))
print(arr)
print('-'*20)

print('Total sum   :', np.sum(arr))
print('Max of all   :', np.max(arr))
print('Min of all   :', np.min(arr))
print('-'*20)

print('sum of rows   :', np.sum(arr,axis = 1))
print('max of rows   :', np.max(arr,axis = 1))
print('min of rows   :', np.min(arr,axis = 1))
print('-'*20)

print('sum of columns   :', np.sum(arr,axis = 0))
print('max of columns   :', np.max(arr,axis = 0))
print('min of columns   :', np.min(arr,axis = 0))

[[99 19 47 32 34]
 [28 78 91 62 38]
 [74  3  0 12 19]]
--------------------
Total sum   : 636
Max of all   : 99
Min of all   : 0
--------------------
sum of rows   : [231 297 108]
max of rows   : [99 91 74]
min of rows   : [19 28  0]
--------------------
sum of columns   : [201 100 138 106  91]
max of columns   : [99 78 91 62 38]
min of columns   : [28  3  0 12 19]


### 18. Seed function

In [97]:
np.random.seed(3)
arr = np.random.randint(0,20, 10 )
arr

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6], dtype=int32)

In [ ]:
np.sort(arr)

### 19. Sorting in numpy array



In [98]:
np.sort(arr)

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19], dtype=int32)

### 20. Mathematical Operation in Numpy

#### 20.1 Addition

In [99]:
lst1 = [1,2,3,45,5,6]
lst2 = [3,4,5,6,321,213]
arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(arr1+arr2)

[  4   6   8  51 326 219]


#### 20.2 Substraction

In [100]:
lst1 = [1,2,3,45,5,6]
lst2 = [3,4,5,6,321,213]
arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(arr1-arr2)

[  -2   -2   -2   39 -316 -207]


#### 20.3 Multiplication

In [102]:
lst1 = [1,2,3,45,5,6]
lst2 = [3,4,5,6,321,213]
arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(arr1*2)

[ 2  4  6 90 10 12]


#### 20.4 Division

In [104]:
lst1 = [1,2,3,45,5,6]
lst2 = [3,4,5,6,321,213]
arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(arr1 / 2)

[ 0.5  1.   1.5 22.5  2.5  3. ]


#### 20.5 Matrix Multiplication

In [110]:
lst1 = [[1,2,3],[4,5,6],[7,8,9],[34,5,5]]
lst2 = [[4,34,2],[4,324,324],[32,423,42]]
arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(np.matmul(arr1,arr2))

[[ 108 1951  776]
 [ 228 4294 1880]
 [ 348 6637 2984]
 [ 316 4891 1898]]


#### 20.6 Power

In [111]:
lst1 = [1,2,3,45,5,6]
lst2 = [3,4,5,6,321,213]
arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(arr1 ** 2)

[   1    4    9 2025   25   36]


### 21. Percentile Function

In [119]:
arr = np.random.rand(100)

per = np.percentile(arr,50)
print(per)

0.49588434202605597


### 22. Descriptive Statistics

#### 22.1 Mean

In [4]:
lst = [[1,2,3],[4,5,6],[7,8,9],[3,4,5]]
       
arr = np.array(lst)

print('Total          :',arr.mean())
print('Row wise       :',arr.mean(axis = 1))
print('col wise       :', arr.mean(axis = 0))

Total          : 4.75
Row wise       : [2. 5. 8. 4.]
col wise       : [3.75 4.75 5.75]


#### 22.2 Median

In [133]:
lst = [[1,2,3],[4,5,6],[7,8,9],[3,4,5]]
       
arr = np.array(lst)

print('Total          :',np.median(arr))
print('Row wise       :',np.median(arr,axis = 1))
print('col wise       :',np.median(arr,axis = 0))

Total          : 4.5
Row wise       : [2. 5. 8. 4.]
col wise       : [3.5 4.5 5.5]


#### 22.4 Standard Deviation

In [130]:
lst = [[1,2,3],[4,5,6],[7,8,9],[3,4,5]]
       
arr = np.array(lst)

print('Total          :',arr.std())
print('Row wise       :',arr.std(axis = 1))
print('col wise       :', arr.std(axis = 0))

Total          : 2.3139072294858036
Row wise       : [0.81649658 0.81649658 0.81649658 0.81649658]
col wise       : [2.16506351 2.16506351 2.16506351]


#### 22.5 Variance

In [129]:
lst = [[1,2,3],[4,5,6],[7,8,9],[3,4,5]]
       
arr = np.array(lst)

print('Total          :',arr.var())
print('Row wise       :',arr.var(axis = 1))
print('col wise       :', arr.var(axis = 0))

Total          : 5.354166666666667
Row wise       : [0.66666667 0.66666667 0.66666667 0.66666667]
col wise       : [4.6875 4.6875 4.6875]


#### 22.6 Skewness

In [5]:
lst = [[1,2,3],[4,5,6],[7,8,9],[3,4,5]]
       
arr = np.array(lst)

mean_ = np.mean(arr)
stddev = np.std(arr)

skew = np.mean((arr - mean_)**3)/((stddev)**3)
print(skew)

0.2648509236311325


#### 22.7 Kurtosis

In [7]:
lst = [[1,2,3],[4,5,6],[7,8,9],[3,4,5]]
       
arr = np.array(lst)

mean_ = np.mean(arr)
stddev = np.std(arr)

kurt = np.mean((arr - mean_)**4)/((stddev)**4)
print(kurt)

2.1518115338612236


### 23. Filtering an numpy array

In [8]:
arr[arr > 5]

array([6, 7, 8, 9])

### 24. Transposing an array

In [10]:
print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 4 5]]
[[1 4 7 3]
 [2 5 8 4]
 [3 6 9 5]]


### 25. Where function

In [11]:
arr = np.where(arr > 5, 5, arr)
print(arr)

[[1 2 3]
 [4 5 5]
 [5 5 5]
 [3 4 5]]


### 26. Merging Arrays

#### 26.1 Using Concatenate

In [14]:
lst1 = [1,2,3,45,5,6]
lst2 = [3,4,5,6,321,213]

arr1 = np.array(lst1)
arr2 = np.array(lst2)

arr3 = np.concatenate((arr1,arr2))
print(arr3)

[  1   2   3  45   5   6   3   4   5   6 321 213]


#### 26.2 Using vstack and hstack

##### 26.2.1 vstack

In [17]:
lst1 = [1,2,3,45,5,6]
lst2 = [3,4,5,6,321,213]

arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(arr1)
print(arr2)
print('-'*30)
arr3 = np.vstack((arr1,arr2))
print(arr3)

[ 1  2  3 45  5  6]
[  3   4   5   6 321 213]
------------------------------
[[  1   2   3  45   5   6]
 [  3   4   5   6 321 213]]


##### 26.2.2 hstack

In [18]:
lst1 = [1,2,3,45,5,6]
lst2 = [3,4,5,6,321,213]

arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(arr1)
print(arr2)
print('-'*30)
arr3 = np.hstack((arr1,arr2))
print(arr3)

[ 1  2  3 45  5  6]
[  3   4   5   6 321 213]
------------------------------
[  1   2   3  45   5   6   3   4   5   6 321 213]


### 27. Splitting Arrays

##### 27.1 Vsplit

In [30]:
lst = [[1,2,3],[4,5,6],[7,8,9],[3,4,5]]
       
arr = np.array(lst)

print(np.vsplit(arr,2))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9],
       [3, 4, 5]])]


##### 27.2 Hsplit

In [32]:
lst = [[1,2,3],[4,5,6],[7,8,9],[3,4,5]]
       
arr = np.array(lst)

print(np.hsplit(arr,3))

[array([[1],
       [4],
       [7],
       [3]]), array([[2],
       [5],
       [8],
       [4]]), array([[3],
       [6],
       [9],
       [5]])]


##### 27.3 Split Function

In [39]:
lst = [[1,2,3],[4,5,6],[7,8,9],[3,4,5]]
       
arr = np.array(lst)

print(np.split(arr, 2, axis = 0))
print('-'*40)
print(np.split(arr, 3, axis = 1))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9],
       [3, 4, 5]])]
----------------------------------------
[array([[1],
       [4],
       [7],
       [3]]), array([[2],
       [5],
       [8],
       [4]]), array([[3],
       [6],
       [9],
       [5]])]


### 28. Linear Algebra
#### 28.1 Determinant

In [21]:
lst = [[1,2,3],[4,8,6],[7,8,9]]
       
arr = np.array(lst)

print(np.linalg.det(arr))

-36.0


#### 28.2 Transpose

In [23]:
lst = [[1,2,3],[4,8,6],[7,8,9]]
       
arr = np.array(lst)

print(np.transpose(arr))

[[1 4 7]
 [2 8 8]
 [3 6 9]]


#### 28.3 Inverse

In [24]:
lst = [[1,2,3],[4,8,6],[7,8,9]]
       
arr = np.array(lst)

print(np.linalg.inv(arr))

[[-0.66666667 -0.16666667  0.33333333]
 [-0.16666667  0.33333333 -0.16666667]
 [ 0.66666667 -0.16666667  0.        ]]


#### 28.4 Eigen Value & Vectors

In [25]:
lst = [[1,2,3],[4,8,6],[7,8,9]]
       
arr = np.array(lst)

print(np.linalg.eig(arr))

EigResult(eigenvalues=array([17.17951595, -1.09435672,  1.91484078]), eigenvectors=array([[-0.21697305, -0.81008628,  0.2719619 ],
       [-0.5985751 , -0.03000853, -0.76035022],
       [-0.77112291,  0.58554224,  0.5898341 ]]))


#### 28.5 Solving Linear Equations

In [26]:
lst = [[1,2,3],[4,8,6],[7,8,9]]
       
coeff = np.array(lst)
value = np.array([34,56,78])

print(np.linalg.solve(coeff,value))

[-6.00000000e+00 -1.55431223e-15  1.33333333e+01]


### 29. Turning Pictures into Numpy arrays

<img src='background.png'>

In [44]:
from matplotlib.image import imread

img = imread('TORQ 3.png')
print(img.shape)

(2646, 1241, 3)
